# Generated by Django 4.1.7 on 2023-02-23 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Date updated')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.SmallIntegerField(blank=True, choices=[(0, 'BACKLOG'), (1, 'TO DO'), (2, 'DOING'), (3, 'TEST'), (4, 'DONE')], null=True)),
                ('priority', models.SmallIntegerField(blank=True, choices=[(0, 'ALTA'), (1, 'MEDIA'), (2, 'BAJA')], null=True)),
                ('dateline', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Date updated')),
                ('comment', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
