# Generated by Django 4.1.7 on 2023-02-27 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Date updated')),
                ('name', models.SmallIntegerField(blank=True, choices=[(0, 'ALTA'), (1, 'MEDIA'), (2, 'BAJA')], null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Date updated')),
                ('name', models.SmallIntegerField(blank=True, choices=[(0, 'BACKLOG'), (1, 'TO DO'), (2, 'DOING'), (3, 'TEST'), (4, 'DONE')], null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='tasks.priority', verbose_name='Prioridad de la tarea'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.state', verbose_name='Estados de la tarea'),
        ),
    ]
