# Generated by Django 4.1.7 on 2023-02-27 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_priority_state_alter_task_priority_alter_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(choices=[(0, 'ALTA'), (1, 'MEDIA'), (2, 'BAJA')], on_delete=django.db.models.deletion.CASCADE, to='tasks.priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.ForeignKey(choices=[(0, 'BACKLOG'), (1, 'TO DO'), (2, 'DOING'), (3, 'TEST'), (4, 'DONE')], on_delete=django.db.models.deletion.CASCADE, to='tasks.state'),
        ),
    ]
