# Generated by Django 4.1.7 on 2023-03-01 15:03

from django.db import migrations


def migrate(apps, schema_editor):
    Priority = apps.get_model('tasks', 'Priority')
    Priority.objects.create(name="BAJA")
    Priority.objects.create(name="MEDIA")
    Priority.objects.create(name="ALTA")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_priority_task_state'),
    ]

    operations = [
        migrations.RunPython(migrate)
    ]
