# Generated by Django 4.1.7 on 2023-03-02 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_alter_task_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(null=True, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
